CATALOG_NAME = "olist_ecommerce"

RAW_SCHEMA = "raw"
BRONZE_SCHEMA = "bronze"
SILVER_SCHEMA = "silver"
GOLD_SCHEMA = "gold"
SECURITY_SCHEMA = "security"

RAW_VOLUME_PATH = "/Volumes/olist_ecommerce/raw/files"
OLIST_RAW_PATH = f"{RAW_VOLUME_PATH}/olist"

BRONZE_FULL_NAME = f"{CATALOG_NAME}.{BRONZE_SCHEMA}"
SILVER_FULL_NAME = f"{CATALOG_NAME}.{SILVER_SCHEMA}"
GOLD_FULL_NAME = f"{CATALOG_NAME}.{GOLD_SCHEMA}"
SECURITY_FULL_NAME = f"{CATALOG_NAME}.{SECURITY_SCHEMA}"